### PARAMETERS
odometry_encoders:
  ros__parameters:

    # Sim time
    use_sim_time: False

    wheels.radius: 0.02569
    wheels.base_width: 0.30

    base_frame_id: 'base_link'
    odom_frame_id: 'odom'

    ticks.ticks_mode: False
    ticks.ticks_meter: 50 
    ticks.encoder_min: -32768
    ticks.encoder_max: 32768

kinematics:
  ros__parameters:

    # Sim time
    use_sim_time: False

    wheels.radius: 0.02569
    wheels.base_width: 0.30

    close_loop: True
    kp: 0.8
    ki: 2.0
    kd: 0.2

    limited: True
    linear_max: 0.621
    angular_max: 4.84

    


    
